{% set name = "ptpython" %}
{% set version = "3.0.30" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/ptpython-{{ version }}.tar.gz
  sha256: 51a07f9b8ebf8435a5aaeb22831cca4a52e87029771a2637df2763c79d3d8776

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  entry_points:
    - ptpython = ptpython.entry_points.run_ptpython:run
    - ptipython = ptpython.entry_points.run_ptipython:run
    - ptpython3 = ptpython.entry_points.run_ptpython:run
    - ptipython3 = ptpython.entry_points.run_ptipython:run

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - appdirs
    - black
    - jedi >=0.16.0
    - prompt_toolkit >=3.0.43,<3.1.0
    - pygments
    - python >={{ python_min }}

test:
  imports:
    - ptpython
    - ptpython.contrib
  commands:
    - pip check
    - ptpython --help
    - ptipython --help
    - ptpython3 --help
    - ptipython3 --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/prompt-toolkit/ptpython
  summary: Python REPL build on top of prompt_toolkit
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - MementoRC
    - Anthchirp
