{% set name = "ptpython" %}
{% set version = "3.0.20" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ptpython-{{ version }}.tar.gz
  sha256: eafd4ced27ca5dc370881d4358d1ab5041b32d88d31af8e3c24167fe4af64ed6

build:
  number: 2
  skip: true  # [py2k]
  entry_points:
    - ptpython = ptpython.entry_points.run_ptpython:run
    - ptipython = ptpython.entry_points.run_ptipython:run
    - ptpython3 = ptpython.entry_points.run_ptpython:run
    - ptpython3.6 = ptpython.entry_points.run_ptpython:run  # [py==36]
    - ptpython3.7 = ptpython.entry_points.run_ptpython:run  # [py==37]
    - ptpython3.8 = ptpython.entry_points.run_ptpython:run  # [py==38]
    - ptpython3.9 = ptpython.entry_points.run_ptpython:run  # [py==39]
    - ptipython3 = ptpython.entry_points.run_ptipython:run
    - ptipython3.6 = ptpython.entry_points.run_ptipython:run  # [py==36]
    - ptipython3.7 = ptpython.entry_points.run_ptipython:run  # [py==37]
    - ptipython3.8 = ptpython.entry_points.run_ptipython:run  # [py==38]
    - ptipython3.9 = ptpython.entry_points.run_ptipython:run  # [py==39]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - appdirs
    - black
    - importlib-metadata  # [py<38]
    - jedi >=0.16.0
    - prompt_toolkit >=3.0.18,<3.1.0
    - pygments
    - python

test:
  imports:
    - ptpython
    - ptpython.contrib
  commands:
    - pip check
    - ptpython --help
    - ptipython --help
    - ptpython3 --help
    - ptpython3.6 --help  # [py==36]
    - ptpython3.7 --help  # [py==37]
    - ptpython3.8 --help  # [py==38]
    - ptpython3.9 --help  # [py==39]
    - ptipython3 --help
    - ptipython3.6 --help  # [py==36]
    - ptipython3.7 --help  # [py==37]
    - ptipython3.8 --help  # [py==38]
    - ptipython3.9 --help  # [py==39]
  requires:
    - pip

about:
  home: https://github.com/prompt-toolkit/ptpython
  summary: Python REPL build on top of prompt_toolkit
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Anthchirp
